### PR TITLE
fixed globals for dashed modules, allowed fn for naming, addresses #10

### PR DESCRIPTION
**Pull request by KoryNunn**

### CODE REVIEW

**Comment by KoryNunn** [comment]
@unional the ability to pass a function here may support #6

**Comment by unional** [comment]
LGTM 🍻 

#6 is different, it's about excluding dependencies from bundling together.

**Comment by KoryNunn** [comment]
I was just referring to the ability to pass a function to generate the name, this would be required to implement #6, because names need to be generated dynamically.

**Comment by unional** [comment]
I see.

On the other hand, you can have code to read the dependencies and pass in the globalVariable as strings. Of course that means externalizing the `camelCase()` logic.

**Pull request merged**
